// This file is auto generated by Rollout.io SDK during application build process, it should be committed to you repository as part of your code. For more info please checkout the FAQ at http://support.rollout.io

#if defined(__LP64__) && __LP64__
# define CGFLOAT_TYPE double
# define CGFLOAT_IS_DOUBLE 1
# define CGFLOAT_MIN DBL_MIN
# define CGFLOAT_MAX DBL_MAX
#else
# define CGFLOAT_TYPE float
# define CGFLOAT_IS_DOUBLE 0
# define CGFLOAT_MIN FLT_MIN
# define CGFLOAT_MAX FLT_MAX
#endif
typedef CGFLOAT_TYPE CGFloat;

#if !defined(OBJC_HIDE_64) && TARGET_OS_IPHONE && __LP64__
typedef bool BOOL;
#else
typedef signed char BOOL;
#endif

typedef struct __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk {
  CGFloat x;
  CGFloat y;
} __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk;
typedef struct __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 {
  CGFloat width;
  CGFloat height;
} __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4;
typedef struct __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc {
  __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk origin;
  __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 size;
} __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc;
typedef struct __rollout_dummy_struct__oGJjIRDwvikGc$VmbTzB7mtlze8 {
  CGFloat horizontal;
  CGFloat vertical;
} __rollout_dummy_struct__oGJjIRDwvikGc$VmbTzB7mtlze8;
typedef struct __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 {
  unsigned long location;
  unsigned long length;
} __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0;
typedef struct __rollout_dummy_struct__PmDF8pTlRPF4YSGP4FoTnrYnMH8 {
  float redGain;
  float greenGain;
  float blueGain;
} __rollout_dummy_struct__PmDF8pTlRPF4YSGP4FoTnrYnMH8;
typedef struct __rollout_dummy_struct__ylHf5PWUd9V7o6wGLwf3J4w1Aak {
  CGFloat a;
  CGFloat b;
  CGFloat c;
  CGFloat d;
  CGFloat tx;
  CGFloat ty;
} __rollout_dummy_struct__ylHf5PWUd9V7o6wGLwf3J4w1Aak;
typedef struct __rollout_dummy_struct__jviU81zjFf3q9k1qOLfWJKJwUdk {
  float x;
  float y;
} __rollout_dummy_struct__jviU81zjFf3q9k1qOLfWJKJwUdk;
typedef struct __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk {
  long long value;
  int timescale;
  __rollout_enum flags;
  long long epoch;
} __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk;
typedef struct __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc {
  __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk start;
  __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk duration;
} __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc;
typedef struct __rollout_dummy_struct___r1mw5_eDSDuKYvcNFSkfl6zMzk {
  float temperature;
  float tint;
} __rollout_dummy_struct___r1mw5_eDSDuKYvcNFSkfl6zMzk;
typedef struct __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI {
  CGFloat top;
  CGFloat left;
  CGFloat bottom;
  CGFloat right;
} __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI;
typedef struct __rollout_dummy_struct__h4Y3OQy7IUvUhprbWZ1ZvbgAMjA {
  __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc source;
  __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc target;
} __rollout_dummy_struct__h4Y3OQy7IUvUhprbWZ1ZvbgAMjA;
typedef struct __rollout_dummy_struct__Mc97o5fdTlN043SQIt84bABmZj0 {
  long location;
  long length;
} __rollout_dummy_struct__Mc97o5fdTlN043SQIt84bABmZj0;
typedef struct __rollout_dummy_struct__ZssiGLMM9VI_EtRScogFvzRYVIw {
  CGFloat dx;
  CGFloat dy;
} __rollout_dummy_struct__ZssiGLMM9VI_EtRScogFvzRYVIw;
